### ISSUE TITLE
Add a command to set branch protections for given branch

### ISSUE THREAD

**Issue by daften** [digipolisgent/php_scripts_github#3]
These can be the defaults. Important is to check which status checks are available, or see if a repo which doesn't have travis integration, if it doesn't throw an error.

<img width="764" alt="screen shot 2018-01-17 at 13 47 17" src="https://user-images.githubusercontent.com/1221024/35043551-566ec4e0-fb8d-11e7-9acb-d446e3b1d191.png">

**Comment by daften** [comment]
@zero2one agreed?

**Comment by matthijs-va** [comment]
@daften Can this be implemented or are you still waiting on a confirmation?

**Comment by daften** [comment]
@matthijs-va https://media1.tenor.com/images/fc4f2c561623b9c1493a600e5b7fc29e/tenor.gif?itemid=4945942
